### ISSUE TITLE
Growl の場合は appname 等を指定できないとやっぱり不便

### ISSUE THREAD

**Issue by jugyo** [jugyo/notify#3]

**Comment by kristianfreeman** [comment]
@jugyo - can't read Japanese but I'm going to guess this has to do with setting an app name for a Growl notification? If so, I'd like to take a look at implementing this in the next couple days. I'm pretty familiar with the Growl implementation after updating it for v0.5.0. 

Let me know if I'm correct and how I should proceed! ありがとうございます！
